name: hireup
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  dotted_border: ^2.0.0
  flutter_screenutil: ^5.9.3
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.11
  permission_handler: ^12.0.1
  flutter_inappwebview: ^6.1.5
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # حطينا المكتبة هنا في الـ dev_dependencies عشان دي وظيفتها وقت التطوير بس
  flutter_launcher_icons: "^0.13.1" 

# تعريفات الأيقونة لازم تكون بره خالص (على أول السطر) مش تبع حد
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash-removebg-preview 1.png"
  adaptive_icon_background: "#eafaea"

flutter:
  uses-material-design: true
  assets:
    - assets/images/